version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myVisitorCount"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jmwcji6oagme"
s3_prefix = "myVisitorCount"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
