name: SAM Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Lambda/requirements.txt
          pip install moto boto3
        
      - name: Test
        run: python test_handler.py
      - name: Build
        run: sam build
      - name: Deploy
        run: sam deploy --no-fail-on-empty-changeset
